version: '3'
services:
    php:
        image: exercise:latest
        container_name: exercise
        networks:
            - exercise-gateway
        volumes:
            - ./:/app
            - ./docker/nginx/default.conf:/etc/nginx/sites-available/default.conf
        links:
            - mysql
        depends_on:
            - mysql
        ports:
            - 82:80
        tty: true

    mysql:
        image: mysql:5.7
        container_name: exercise_mysql
        environment:
            - MYSQL_ROOT_PASSWORD=qwerty
            - MYSQL_DATABASE=exercise
            - MYSQL_USER=exercise
            - MYSQL_PASSWORD=qwerty
        ports:
            - 3308:3306
        networks:
            - exercise-gateway
        volumes:
            - my-datavolume:/var/lib/mysql

networks:
    exercise-gateway:
        external: true

volumes:
    my-datavolume:
